### ISSUE TITLE
Error creating service

### ISSUE THREAD

**Issue by safurniss** [jephthai/OpenPasswordFilter#1]
The instructions mention to use sc.exe to create the service using the following command:-

`sc create OPF binPath= c:\opf\opfservice.exe start= boot`

If I try using the "start= boot" parameter then I get **[SC] CreateService FAILED 87:**

If I change the parameter to "auto" then it will create the service.

Is this due to a specific binPath requirement when using " boot" as the start parameter?

**Comment by jephthai** [comment]
Steve:

Thanks for your interest!  That line is exactly what I used during testing,
so I'm confused why it doesn't work.  Error 87 is an incorrect parameter,
but I'm at a loss for what's wrong with it.  I did my testing on Server
2008 -- what Windows are you using?

-Josh Stone-

**Comment by safurniss** [comment]
I've tried it on both 2008 R2 and 2012 R2... I get the same error...

I also ensured that the command prompt was run as administrator to make sure that it wasn't a permissions thing.

I did find an article that mentioned you had to put things in %SystemRoot%\System32\drivers if they were to run with a start mode of boot... but couldn't get it working that way either.

Here is the link to the article that I found:-
http://microsoft.public.win32.programmer.kernel.narkive.com/zkVmV2Fz/problem-using-changeserviceconfig-to-set-a-driver-to-boot-start

Regards

Steve

**Comment by aleck011mi** [comment]
I was able to get around this issue by changing "boot" to "demand" in Server 2012. Boot was only supported in 2003 and earlier if I remember correctly. I'm having a problem with getting the service to start though.

**Comment by aleck011mi** [comment]
I solved the service not starting by installing .NET Framework 3.5

**Comment by choakumchild** [comment]
This dont work very good... Worked on first time that I implement, but no longer worked...

One more thing, I want to restrict the word "password" of all passwords. For example password1, password123 etc, is this possible?

**Comment by jephthai** [comment]
Thanks for reporting your experience -- I will get my test rig up and do some checking, myself.  As far as matching substrings, that would be pretty easy to add -- I'll put it on the list.  I'll comment back here once I confirm that the code is at least working on my end.

**Comment by choakumchild** [comment]
Ok..
If I reboot it work again...
If you can make this restricting words, like "password" of all passwords. For example password1, password123 etc, is this possible?

**Comment by nelideven** [comment]
"boot" and "system" don't work if type=own (or that's the default usually) because according to one of Microsoft Articles (https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create) says that both "boot" and "system" start type is used for drivers, not services

**Comment by nelideven** [comment]
> "boot" and "system" don't work if type=own (or that's the default usually) because according to one of Microsoft Articles (https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create) says that both "boot" and "system" start type is used for drivers, not services

So if you want to make a service, the start type should be "auto" or lower
