### ISSUE TITLE
Error code 577: Failed to load

### ISSUE THREAD

**Issue by randumbguy** [jephthai/OpenPasswordFilter#12]
Testing on 2k12 R2 and I get the following error message, which I was thinking might be due to lack of digital signature.  I tried the new path specifications, with no success.

"The password notification DLL OpenPasswordFilter failed to load with error 577. Please verify that the notification DLL path defined in the registry, HKLM\System\CurrentControlSet\Control\Lsa\Notification Packages, refers to a correct and absolute path (<drive>:\<path>\<filename>.<ext>) and not a relative or invalid path. If the DLL path is correct, please validate that any supporting files are located in the same directory, and that the system account has read access to both the DLL path and any supporting files.  Contact the provider of the notification DLL for additional support. Further details can be found on the web at http://go.microsoft.com/fwlink/?LinkId=245898."

**Comment by brockrob** [comment]
Odd, none of my testing has required that DLL be signed. MS documentation says you're right about 577 being related to signing. My testing has been on a very fresh 2k12 R2 domain in a lab - do you have some non-default hardening tweaks applied by chance? It does seem to me to be a good idea not to load unsigned DLLs into lsass.exe...

**Comment by randumbguy** [comment]
So far I've disabled general signing requirements as well as safe dll search.  I also completely removed any security tools that might interfere, as this is only a dev/test system.  I'm still seeing the same error message.  As far as policy changes or additional hardening steps are concerned, this is fresh virtual with all patches installed.  The only changes so far have been to install directory services and attempt to get the password filter working.

**Comment by randumbguy** [comment]
Okay, I guess sometimes I just forget things.  This was caused by our build process.  A deployment server streamlines the process.  There is a post build step that enables lsass protection.  After disabling this, the dll loads fine.  Application whitelisting would be able to permit this and block other interactions.  The specific setting was at: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa.  The key is RusAsPPL.  Enabled is 1 and Disabled is 0.
