### ISSUE TITLE
Initial required password change accepts every password

### ISSUE THREAD

**Issue by dnzmartijnkamminga** [jephthai/OpenPasswordFilter#14]
Hi There,

I have a problem with this Open Password Filter.

I've setup a test environment and used the all-in-one installer.
Upon creating my first dictionary, it rejected one password, once.

After that, everything was possible.

Your readme is not up to date with your changes, so I snoofed arround to get things going.
It is a succes, when a user uses the CTRL ALT DEL option. Yes, then it's rejected.
But not on a password reset from the AD-DC. You can choose any password you want.

How can I, or you program it, so that the initial password change is required to meet those strengths from the exact, partial and excluded .txt ?

Love to hear from you,

Kind regards,

Martijn Kamminga

**Comment by mwtrigg** [comment]
I can not replicate this issue; currently running software compiled on 8 Mar 2017 with custom opfcont and opfmatch files.

**Comment by dnzmartijnkamminga** [comment]
I have Server 2016 Standard x64. Is it unsupported?

**Comment by dnzmartijnkamminga** [comment]
And besides: you tell to put the checkfiles within the folder of the executable. Mine is in the program files x64 directory.

Does that mean that it's not looking in system32 at all? Or could there be some mixup?

**Comment by dnzmartijnkamminga** [comment]
Hi,

I've put keywords in exact, partial but not excluded. and put those keywords also in the opf files.
I've copied the dictionary's to system32 as well as the opf directory and now it works.
I'm going to test this one more time, to see which files are mandatory where.
I do doubt about the exact match filter. 
Is there a file format such as UTF/ANSI mandatory?

**Comment by dnzmartijnkamminga** [comment]
Hi there,

Well, tested and confirmed.

Environment:
Server 2016 Standard - AD / DHCP / DNS
Client: Windows 10 1709 VL

Problem:
opfcont.txt is the only file that is processed by OPFService.exe

Solution:
If you want exact to be filtered you'd have to type in the whole KeyW0Rd!
That will be denied as well, even in AD pwd reset for a user account.
The partial works too, but be carefull, to less words, will block very much possbility's.

Unless:
You can get me up to date why 
- opfmatch.txt is not processed
- exact partial and excluded are not working

Kind regards,

Martijn Kamminga

**Comment by dnzmartijnkamminga** [comment]
Ok, don't know why, don't know how, but after a couple of reboots of the AD it worked.
I noticed upon restarting the service, one time it started extremely fast, the other time, because of the dictionary's, it took a while. Maybe it did not get processed those other times.

Also, I noticed, when restarting the service and stripping the word lists, what was added, stay's, and you need a reboot of your AD to clear the settings for the stripped dictionary file to be effective.

Anyway, thank you very much for your efforts! It is most welcome to use! Searched allot on the internet, so your service and contribution is well appreciated! 

Thank you very much!
