### ISSUE TITLE
stand back ... i've had a thought...

### ISSUE THREAD

**Issue by subrosaassociates** [jephthai/OpenPasswordFilter#33]
- Evaluate the strength of a password/passphrase _then_ assign them a group

- Define groups of varying lengths, such as crappass_group=30 days, OK_group=60 , Good 90 etc... 

this could be huge in influence 

I'm coming in hot to this project so apologies if there is a world of problems to why this might be easier said than done, but from a users perspective, i think it would be fantastic, and worthwhile 

No ?

this would passively promote willingness to give a stronger password to be 'bothered less' by the process of changing and using a new one

**Comment by mwtrigg** [comment]
Interesting idea, but the result would be that you are explicity highlighting to users, admins, and potential malicious actors which accounts have crappy passwords and which accounts have "strong" passwords.  Moreover, this project doesn't actually evaluate the strength of a password - it is a tool to provide a means of preventing undesireable passwords from being used.

**Comment by subrosaassociates** [comment]
Hey @mwtrigg, thanks for the reply! :) I guess I'm barking up the wrong tree huh, I agree with your point on policy exposure but I assume the same case could be made for FGPP, from an enumeration perspective, the goal for me in this was to encourage people to move from low complexity to passphrases ... I can see why it's out of scope, but still think it's valuable, if you fine people know anyone that might have the will, i think it would be an excellent option for UX and easing changes in big slow moving orgs

**Comment by mwtrigg** [comment]
FGPP would only disclose whether or not complexity was enabled and the minimum length of the password - it wouldn't disclose to anybody (admin, co-workers or malcontents) the objective quality of the password.  Although, I guess objective quality of a password can be somewhat nebulous.

I do leverage FGPPs for this purpose, but it is more of an _opt-in_ process.  An initial offer went out, and is extended everytime I am approached by somebody about password rotation.  If a colleague agrees to a minimum of 15 characters, their account will be subjected to a FGPP with a 15 character minimum and a 365 day rotation (still can't get C-levels to agree to no expiration).

I just don't think this is the appropriate tool for the job.  To me, the purpose of the tool is to prevent undesireable passwords -- to flip it on its side and also use it to allow bad passwords and just flag the account for heavy rotation seems contrary to its intended purpose.  I'm just a user of the filter; just one unsolicited opinion.

If it interests you though, you should try some of the forks of this project that are being actively developed.  This one does not appear to be recently active.

**Comment by subrosaassociates** [comment]
Thanks for your time @mwtrigg :) I think for now i'll pinch your opt-in process that's probably the best available path for what i'm looking to do :), i'll close this now - apologies for the scope creep!
