### ISSUE TITLE
SecureZeroMemory Call

### ISSUE THREAD

**Issue by ljr55555** [jephthai/OpenPasswordFilter#4]
I used this project as a base for a password filter with different logic, and it worked perfectly in my tests (password change and bind via LDAP to verify). It, however, failed when someone attempted to log into a workstation. In fact, you could log in with a BLANK password. 

AD computes the ntlm one way hash, calls the filters, and then proceeds to compute the hashes used for kerberos and such. The technet article meant that they assume you've made copies of the password somewhere within your code & you need to run SecureZeroMemory on any copies that you've made *but* they need the PUNICODE_STRING that got passed in to be left alone. And, yes, they will handle *that* copy when their processes are done. Otherwise the password works for some authentication methods and is NULL for others. 

	// MS documentation suggests doing this.  I honestly don't know why LSA
	// doesn't just do this for you after we return.  But, I'll do what the
	// docs say...
	// LJR - 2016-12-15 - Per MS, they actually mean to wipe any COPIES you make 
	//	SecureZeroMemory(Password->Buffer, Password->Length);

**Comment by jephthai** [comment]
Wow, thanks!  That explains it all.  I removed that call, and now a couple other issues have disappeared.  I updated the code, as you suggest.  Thanks much!
