### ISSUE TITLE
No effect on Windows 7 x86?

### ISSUE THREAD

**Issue by CaledoniaProject** [jephthai/OpenPasswordFilter#8]
I've successfully installed the binary release version,

Created `c:\windows\system32\opfmatch.txt` and verified `LSA notification package` key is correctly set, but `net user` command still completes successfully .. any ideas?

![screen 2017-03-14 at 17 35 44](https://cloud.githubusercontent.com/assets/1357701/23894355/b78cda68-08dc-11e7-9e42-8817d6b586db.jpg)

**Comment by brockrob** [comment]
My bad - the readme is out of sync. It now looks for the lists in the same directory where the service .exe lives. If you used the installers, it'll be in c:\program files\openpasswordfilter or similar.

**Comment by CaledoniaProject** [comment]
Still no effect ..

I've found the files you mentioned, in `C:\Program Files\OpenPasswordFilter\OpenPasswordFilter`

![screen 2017-03-14 at 19 02 51](https://cloud.githubusercontent.com/assets/1357701/23897635/da6ac4c6-08e8-11e7-8379-b460aeb304b9.jpg)

**Comment by brockrob** [comment]
Ok, I didn't test on x86 myself. Sounds like the filter dll may not be loaded correctly. Did you reboot after installation? If so, is there anything in the System event log? This article talks about the log entries that can be expected should loading the dll fail:

https://support.microsoft.com/en-us/help/2686224/how-to-configure-and-troubleshoot-external-password-filters-in-windows-8-and-in-windows-server-2012

**Comment by CaledoniaProject** [comment]
Oh sure, I'll find a x64 server and test it again

**Comment by CaledoniaProject** [comment]
Okay, works on windows 2008 R2 x64, fails on windows 7 sp1 x86

**Comment by brockrob** [comment]
Hmm, could you check that event log for me and see if there's any messages about why the dll is failing to load? I wonder if there's a runtime dependency (some msvcr**.dll) or something that I need to ship with the x86 installer?

I also question whether we even need to target x86. Server 2008 is the last server OS even available for 32 bit platforms, isn't it?

**Comment by CaledoniaProject** [comment]
Building with the source code works for me :-P
